### GET all persons
GET http://localhost:3001/api/persons
content-type: application/json

### GET single person
GET http://localhost:3001/api/persons/6574904d668921469ea85a2b
content-type: application/json

### DELETE single person
DELETE http://localhost:3001/api/persons/657490a985d2a70a94c7046e
content-type: application/json

### Create a single person
POST http://localhost:3001/api/persons/
content-type: application/json

{ 
    "name": "mongo person", 
    "number": "1143526756"
}

### Create a single person without name - Error
POST http://localhost:3001/api/persons/
content-type: application/json

{ 
    "number": "1143526756"
}

### Create a single person without number - Error
POST http://localhost:3001/api/persons/
content-type: application/json

{ 
    "name": "test"
}

### Create a single person that is already in the phonebook - Error
POST http://localhost:3001/api/persons/
content-type: application/json

{ 
    "name": "Ada Lovelace",
    "number": "123-3123-312"
}

### Create a single person that is already in the phonebook - Error
PUT http://localhost:3001/api/persons/65749e3a2d18caf26a6c19ed
content-type: application/json

{ 
    "name": "new person for MB",
    "number": "123-3123-312"
}

